### ISSUE TITLE
composer ApiError.php

### ISSUE THREAD

**Issue by andygithubchen** [coingate/coingate-php#11]
**I use composer install**

```shell
composer require coingate/coingate-php
```

**And test :**
```php
$testConnection = \CoinGate\CoinGate::testConnection(array(
  'environment'   => 'sandbox',
  'auth_token'    => 'YOUR_AUTH_TOKEN'
));

if ($testConnection !== true) {
  echo $testConnection; // CoinGate\BadCredentials: BadCredentials Not found App by Access-Key
}
```

**Get error info:**
```shell
PHP Fatal error:  Uncaught Error: Class 'CoinGate\BadAuthToken' not found in /root/coding/video/video/vendor/coingate/coingate-php/lib/Exception.php:39
Stack trace:
#0 /root/coding/video/video/vendor/coingate/coingate-php/lib/CoinGate.php(89): CoinGate\Exception::throwException(401, Array)
#1 /root/coding/video/video/vendor/coingate/coingate-php/lib/CoinGate.php(32): CoinGate\CoinGate::request('https://api-san...', 'GET', Array, Array)
#2 /root/coding/video/video/app/modules/cli/tasks/TimeTask.php(20): CoinGate\CoinGate::testConnection(Array)
#3 /root/coding/video/video/app/modules/cli/tasks/TimeTask.php(14): Web\Modules\Cli\Tasks\TimeTask->_test()
#4 [internal function]: Web\Modules\Cli\Tasks\TimeTask->mainAction(Array, Array)
#5 [internal function]: Phalcon\Cli\Dispatcher->callActionMethod(Object(Web\Modules\Cli\Tasks\TimeTask), 'mainAction', Array)
#6 [internal function]: Phalcon\Dispatcher->dispatch()
#7 /root/coding/video/video/app/bootstrap_cli.php(40): Phalcon\Cli\Console->handle(Array)
#8 /root/coding/video/video/publi in /root/coding/video/video/vendor/coingate/coingate-php/lib/Exception.php on line 39
```

**I think Exception.php not include ApiError.php file by composer**

**Comment by vgumonis** [comment]
Hi andygithubchen,
We recently made a new release of our library which improves Composer compatibility. Please update to our new release.
